Workflow changes

diff --git a/.github/workflows/DeployApiTooVPS.yaml b/.github/workflows/DeployApiTooVPS.yaml
--- a/.github/workflows/DeployApiTooVPS.yaml
+++ b/.github/workflows/DeployApiTooVPS.yaml
@@ -4,8 +4,8 @@ on:
   push:
     branches:
       - main
-    #paths:
-    #  - 'FoosballProLeague.Api/**'
+    # paths:
+    #   - 'FoosballProLeague.Api/**'
 
 jobs:
   build-and-test:
@@ -38,6 +38,7 @@ jobs:
             }
           }' > FoosballProLeague.Api/FoosballProLeague.Api.Tests/appsettings.test.json
 
+      # Uncomment below if you want to run tests
       #- name: Run tests
       #  run: dotnet test FoosballProLeague.Api/FoosballProLeague.Api.Tests/FoosballProLeague.Api.Tests.csproj --verbosity normal
 
@@ -87,11 +88,24 @@ jobs:
           username: ${{ secrets.DIGITAL_OCEAN_USER }}
           key: ${{ secrets.DIGITAL_OCEAN_SSH_KEY }}
           script: |
+            # Ensure any old containers and images are removed
             docker stop foosballproleague-api-container || true
             docker rm foosballproleague-api-container || true
             docker image rm -f foosballproleague-api:latest || true
             docker image prune -f
-            docker load -i /root/foosballproleague-api.tar
+
+            # Load the docker image from tar file
+            if [ -f /root/foosballproleague-api.tar ]; then
+              docker load -i /root/foosballproleague-api.tar
+            else
+              echo "Docker image file not found!"
+              exit 1
+            fi
+
+            # Verify the image is loaded
+            docker images
+
+            # Run the container
             docker run -d -p 5001:5001 \
             --name foosballproleague-api-container \
             -e ConnectionStrings__DatabaseConnection="${{ secrets.DATABASE_CONNECTION_STRING }}" \
